In [8]:
# import base packages
import pandas as pd
import requests
import os

In [28]:
# Get the station data in the API
url='https://gbfs.divvybikes.com/gbfs/en/station_information.json'
r = requests.get(url)
json = r.json()
station = pd.DataFrame(json['data']['stations'])
station.head()

,external_id,station_id,short_name,eightd_has_key_dispenser,legacy_id,electric_bike_surcharge_waiver,capacity,has_kiosk,rental_methods,name,...,station_type,eightd_station_services,region_id,region_code,address,dockless_bikes_parking_zone_capacity,rack_model,client_station_id,target_bike_capacity,target_scooter_capacity
0,a3b1c47b-a135-11e9-9cda-0a87ae2ba916,a3b1c47b-a135-11e9-9cda-0a87ae2ba916,16915,False,541,False,11,True,"[KEY, CREDITCARD, TRANSITCARD]",Central Ave & Harrison St,...,classic,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,a3b2d2b7-a135-11e9-9cda-0a87ae2ba916,a3b2d2b7-a135-11e9-9cda-0a87ae2ba916,593,False,593,False,11,True,"[KEY, CREDITCARD, TRANSITCARD]",Halsted St & 59th St,...,classic,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,a3b20960-a135-11e9-9cda-0a87ae2ba916,a3b20960-a135-11e9-9cda-0a87ae2ba916,554,False,554,False,7,True,"[KEY, CREDITCARD, TRANSITCARD]",Damen Ave & 51st St,...,classic,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,a3a5f5e6-a135-11e9-9cda-0a87ae2ba916,a3a5f5e6-a135-11e9-9cda-0a87ae2ba916,13162,False,135,False,11,True,"[KEY, CREDITCARD, TRANSITCARD]",Halsted St & 21st St,...,classic,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,a3a795d7-a135-11e9-9cda-0a87ae2ba916,a3a795d7-a135-11e9-9cda-0a87ae2ba916,13036,False,197,False,19,True,"[KEY, CREDITCARD, TRANSITCARD]",Michigan Ave & Madison St,...,classic,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
# Check the station_df columns
station.columns

Index(['external_id', 'station_id', 'short_name', 'eightd_has_key_dispenser',
       'legacy_id', 'electric_bike_surcharge_waiver', 'capacity', 'has_kiosk',
       'rental_methods', 'name', 'lon', 'rental_uris', 'lat', 'station_type',
       'eightd_station_services', 'region_id', 'region_code', 'address',
       'dockless_bikes_parking_zone_capacity', 'rack_model',
       'client_station_id', 'target_bike_capacity', 'target_scooter_capacity'],
      dtype='object')

In [35]:
# export the data to a csv file
os.makedirs('raw_data', exist_ok=True)  
station.to_csv('raw_data/station_API.csv')

In [3]:
# test the get_station_data function
from ml_logic.data_import import get_station_data

df = get_station_data()
df

,Unnamed: 0,external_id,station_id,short_name,eightd_has_key_dispenser,legacy_id,electric_bike_surcharge_waiver,capacity,has_kiosk,rental_methods,...,station_type,eightd_station_services,region_id,region_code,address,dockless_bikes_parking_zone_capacity,rack_model,client_station_id,target_bike_capacity,target_scooter_capacity
0,0,a3b1c47b-a135-11e9-9cda-0a87ae2ba916,a3b1c47b-a135-11e9-9cda-0a87ae2ba916,16915,False,541,False,11,True,"['KEY', 'CREDITCARD', 'TRANSITCARD']",...,classic,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,a3b2d2b7-a135-11e9-9cda-0a87ae2ba916,a3b2d2b7-a135-11e9-9cda-0a87ae2ba916,593,False,593,False,11,True,"['KEY', 'CREDITCARD', 'TRANSITCARD']",...,classic,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,a3b20960-a135-11e9-9cda-0a87ae2ba916,a3b20960-a135-11e9-9cda-0a87ae2ba916,554,False,554,False,7,True,"['KEY', 'CREDITCARD', 'TRANSITCARD']",...,classic,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,a3a5f5e6-a135-11e9-9cda-0a87ae2ba916,a3a5f5e6-a135-11e9-9cda-0a87ae2ba916,13162,False,135,False,11,True,"['KEY', 'CREDITCARD', 'TRANSITCARD']",...,classic,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,a3a795d7-a135-11e9-9cda-0a87ae2ba916,a3a795d7-a135-11e9-9cda-0a87ae2ba916,13036,False,197,False,19,True,"['KEY', 'CREDITCARD', 'TRANSITCARD']",...,classic,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1417,1417,motivate_CHI_1715846688321143644,1715846688321143644,NaN,False,1715846688321143644,False,1,False,NaN,...,lightweight,[],NaN,CHI,"2609, West Division Street, West Town, Chicago...",1.0,CITY_PUBLIC_RACK,motivate_CHI_1715846688321143644,NaN,NaN
1418,1418,motivate_CHI_1715823822654071770,1715823822654071770,NaN,False,1715823822654071770,False,1,False,NaN,...,lightweight,[],NaN,CHI,"2237, West 50th Place, Gage Park, Chicago, Lak...",1.0,CITY_PUBLIC_RACK,motivate_CHI_1715823822654071770,NaN,NaN
1419,1419,motivate_CHI_1563698701206292480,1563698701206292480,NaN,False,1563698701206292480,False,9,False,NaN,...,lightweight,[],NaN,CHI,"3218-3220, North Lamon Avenue, Portage Park, C...",9.0,CITY_PILOT_RACK,motivate_CHI_1563698701206292480,NaN,NaN
1420,1420,motivate_CHI_1674190591734328324,1674190591734328324,NaN,False,1674190591734328324,False,2,False,NaN,...,lightweight,[],NaN,CHI,"Dr. Martin Luther King, Jr. Family Entertainme...",2.0,CITY_PUBLIC_RACK,motivate_CHI_1674190591734328324,NaN,NaN
1421,1421,motivate_CHI_1674190634684001360,1674190634684001360,NaN,False,1674190634684001360,False,2,False,NaN,...,lightweight,[],NaN,CHI,"Susan B. Anthony Elementary School, East 99th ...",2.0,CITY_PUBLIC_RACK,motivate_CHI_1674190634684001360,NaN,NaN